### ISSUE TITLE
Atom v1.0

### ISSUE THREAD

**Issue by mj41** [jamesnetherton/docker-atom-editor#4]
Please update to version 1.0
* http://blog.atom.io/2015/06/25/atom-1-0.html
* http://www.reddit.com/r/programming/comments/3b2w1i/atom_10/

Thanks a million.

**Comment by jamesnetherton** [comment]
All done. Had to do the updates from my cell phone so did not get a chance to test the final image.

Dockerhub says they built ok so hopefully it'll work fine.
