### ISSUE TITLE
Fetch latest?

### ISSUE THREAD

**Issue by stramel** [jamesnetherton/docker-atom-editor#41]
I'm not too good at docker but wondering if you can do something like

```
ENV ATOM_VERSION $(curl -sX GET  "https://api.github.com/repos/atom/atom/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
```

or 

```
docker run -e ATOM_VERSION $(curl -sX GET  "https://api.github.com/repos/atom/atom/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
```

**Comment by jamesnetherton** [comment]
Are you wanting to run the latest version of this image? The latest Atom version is always tagged on the image as 'latest'. So running:

`docker run jamesnetherton/docker-atom-editor`

Will always pull the latest image (and therefore Atom version). Else there are [specific version tags](https://hub.docker.com/r/jamesnetherton/docker-atom-editor/tags/).

AFAIK dynamic resolution of ENV vars is not possible when building images (especially on Docker Hub). The ENV var value ends up being set to the variable expression:

```
Sending build context to Docker daemon 
Step 0 : FROM alpine:latest
 ---> f58d61a874be
Step 1 : ENV FOO $(echo bar)
 ---> Using cache
 ---> d85d6380f0f4
Step 2 : RUN echo $FOO
 ---> Running in 28d34e82d41b
$(echo bar)
 ---> 55e319807d6c
```

I have a [script](https://github.com/jamesnetherton/docker-atom-editor/blob/master/update.sh) that keeps things up-to-date for me.

**Comment by stramel** [comment]
Gotcha, was thinking there may be a way to not have a script that makes you commit and stay up to date with it. Adding the `-e ATOM_VERSION ...` to your `docker run` command should fix that but requires you to enter it each time.

**Comment by jamesnetherton** [comment]
Ideally you want the update to happen at build time, not at run time. Otherwise there's not guarantee that the base image will even support Atom as it changes over time (it may require additional libraries etc).

I'll stick with the update script for now. It's triggered each day by cron, so all I have to do is update the tag on Docker Hub and force a build.

Thanks for taking the time to contribute :smile:
