### ISSUE TITLE
What is the `-v /dev/shm:/dev/shm` used for?

### ISSUE THREAD

**Issue by auzias** [jamesnetherton/docker-atom-editor#56]
I'm just wondering why this volume is mounted. Why does Atom need it?

**Comment by jamesnetherton** [comment]
IIRC Docker defaults the size of `/dev/shm `to 64MB, so mounting this from the host is usually a simple way of increasing this. The alternative is to provide the `--shm-size` flag.

I guess this is not strictly necessary for Atom, so it could probably be removed from the README. It may have been something that I copy / pasted from one of my other images by mistake.

**Comment by auzias** [comment]
Thanks! I did not know about that, although I'll rather go with a flag than a mounted volume as you suggested.

Thanks for the fast reply and the details!

**Comment by auzias** [comment]
Can be fixed by PR #60.
