### ISSUE TITLE
Will this work on Windows

### ISSUE THREAD

**Issue by namelus** [jamesnetherton/docker-atom-editor#92]
Hi James

I'm using Docker Toolbox on Windows 10 Home.
I've built the image and run this per the Readme, but I am not actually sure how to connect to the container via VNC.

I'm new to all this, btw.

Thanks

**Comment by jamesnetherton** [comment]
Hello!

Short answer - I have no idea. 

I've never run Docker on Windows, so I'm not sure how GUI based apps from Linux images are supposed to work.

If you want to connect via VNC then that implies (to me) that there needs to be a VNC server running in the container. So you could maybe extend the image and add this.

If I get time over the next few days I'll try to research and experiment how things are meant to work on Windows.

**Comment by namelus** [comment]
Makes sense.

I suspected that.

Thanks James.

--
Suleman
905-299-6578

sent from mobile
