### ISSUE TITLE
libgtk-3-0 and Atom v1.28.0

### ISSUE THREAD

**Issue by Arcanemagus** [jamesnetherton/docker-atom-editor#93]
Since it looks like you only build the stable releases here, I figured I would give you a heads up that you will need to modify the dependencies installed for Atom to switch from `libgtk2.0-0` to `libgtk-3-0` when Atom v1.28.0 releases to stable.

I noticed the dependency was missing in my [own builds](https://hub.docker.com/r/arcanemagus/atom-docker-ci/) meant for CI only, and got it fixed at the source in https://github.com/atom/atom/pull/17350, but as only incredibly minimal installations like Docker containers would hit that it wasn't deemed necessary to hotfix it.

Just a friendly heads up!

**Comment by jamesnetherton** [comment]
Many thanks for the heads up about this :1st_place_medal:.
