### ISSUE TITLE
Run as root user

### ISSUE THREAD

**Issue by ItBankB** [jamesnetherton/docker-atom-editor#95]
Tell me please!
How to run the image after the image is assembled, the application is not under the user "atom", but under "root"&
Thank!

**Comment by jamesnetherton** [comment]
Hello,

Do you just want to know how to run an Atom container?

There's an instruction in the README:

```
docker run -d -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
              -v /dev/shm:/dev/shm \
              -v ${HOME}/.atom:/home/atom/.atom \
              -e DISPLAY \
              jamesnetherton/docker-atom-editor
```
