### ISSUE TITLE
Removing the line USER atom

### ISSUE THREAD

**Issue by xiaodaigh** [jamesnetherton/docker-atom-editor#98]
If I keep the line `USER atom` then it doesn't work. If I remove it then it works. I am ssh-into a remote server, so that's another layer of complexity.

Running it on Windows WSL also doesn't work with removing the line USER atom. 

and thank you for this docker file.

**Comment by jamesnetherton** [comment]
Are you saying that the container **_does not_** run when removing the `USER` directive?

Testing on Fedora, it works fine for me when `USER` is removed.

I'm curious why you want to do this though. It means the Atom process ends up running as `root`, which is considered bad practice.

**Comment by xiaodaigh** [comment]
Updated now as I writing the stuff on the train.

Removing USER is the only way for me to make it work. I am running inside docker so it's not really an issue to use root right?

**Comment by jamesnetherton** [comment]
Its a misconception to think that running as root does not matter just because the app is running inside of a container:

https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

https://americanexpress.io/do-not-run-dockerized-applications-as-root/
